CREATE USER test PASSWORD 'test';

CREATE DATABASE tm351test;

GRANT ALL PRIVILEGES ON DATABASE tm351test TO test;

CREATE ROLE root WITH SUPERUSER LOGIN;

CREATE USER tm351admin WITH PASSWORD 'tm351admin' SUPERUSER;


